# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.kyc.com:
  peer0.citiBank.kyc.com:
  peer1.citiBank.kyc.com:
  peer0.sbi.kyc.com:
  peer1.sbi.kyc.com:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-citiBank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.citiBank.kyc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.citiBank.kyc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/citiBank.kyc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCitiBank
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-sbi
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.sbi.kyc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.sbi.kyc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/sbi.kyc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSBI
    networks:
      - byfn

  orderer.kyc.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.kyc.com
    container_name: orderer.kyc.com
    networks:
      - byfn

  peer0.citiBank.kyc.com:
    container_name: peer0.citiBank.kyc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.citiBank.kyc.com
    networks:
      - byfn

  peer1.citiBank.kyc.com:
    container_name: peer1.citiBank.kyc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.citiBank.kyc.com
    networks:
      - byfn

  peer0.sbi.kyc.com:
    container_name: peer0.sbi.kyc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.sbi.kyc.com
    networks:
      - byfn

  peer1.sbi.kyc.com:
    container_name: peer1.sbi.kyc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.sbi.kyc.com
    networks:
      - byfn
